import trex
import graphviz

# 1. Load the JSON data generated by trtexec
plan = trex.EnginePlan(
    "layer_info.json",
    "profile.json"  # Optional: remove if you didn't generate profile data
)

# 2. Create the Graphviz object
# This formats the graph, grouping fused layers together
graph = trex.to_dot(plan, layer_type_color_dict=trex.layer_type_color_dict)

# 3. Render and save as SVG
# This will create 'engine_graph.svg'
output_path = "engine_graph"
graph.render(filename=output_path, format="svg", cleanup=True)

print(f"Graph saved to {output_path}.svg")
